name: Kraken 12H Trend Alert

on:
  schedule:
    - cron: '52 0 * * *'
    - cron: '53 12 * * *'  
  workflow_dispatch:
  
jobs:
  check_ma_crossover:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ccxt requests pandas python-telegram-bot pytz

      - name: Download Python time script
        run: curl -o time_check.py ${{ secrets.TIME }}

      - name: Run Telegram message script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python time_check.py

      - name: Download Python script
        run: curl -o rotify.py ${{ secrets.CHECKER }}

      - name: Verify script download
        run: head -n 10 rotify.py

      - name: Print current UTC time
        run: date -u

      - name: Run MA crossover check
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python rotify.py
